<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ros" nsURI="http://www.ipa.fraunhofer.de/ros" nsPrefix="ros">
  <eClassifiers xsi:type="ecore:EClass" name="Node">
    <eStructuralFeatures xsi:type="ecore:EReference" name="serviceserver" upperBound="-1"
        eType="#//ServiceServer" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="publisher" upperBound="-1"
        eType="#//Publisher" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subscriber" upperBound="-1"
        eType="#//Subscriber" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="serviceclient" upperBound="-1"
        eType="#//ServiceClient" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="actionserver" upperBound="-1"
        eType="#//ActionServer" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="actionclient" upperBound="-1"
        eType="#//ActionClient" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="#//GraphName"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameter" upperBound="-1"
        eType="#//Parameter" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Package">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="spec" upperBound="-1" eType="#//SpecBase"
        containment="true" eOpposite="#//SpecBase/package"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="artifact" upperBound="-1"
        eType="#//Artifact" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fromGitRepo" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dependency" upperBound="-1"
        eType="#//Dependency" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Dependency" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="ServiceSpec" eSuperTypes="#//SpecBase">
    <eStructuralFeatures xsi:type="ecore:EReference" name="request" eType="#//MessageDefinition"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="response" eType="#//MessageDefinition"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ServiceServer" eSuperTypes="#//NamespacedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="service" lowerBound="1"
        eType="#//ServiceSpec"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TopicSpec" eSuperTypes="#//SpecBase">
    <eStructuralFeatures xsi:type="ecore:EReference" name="message" eType="#//MessageDefinition"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PackageDependency" eSuperTypes="#//Dependency">
    <eStructuralFeatures xsi:type="ecore:EReference" name="package" lowerBound="1"
        eType="#//Package"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExternalDependency" eSuperTypes="#//Dependency">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CatkinPackage" eSuperTypes="#//Package"/>
  <eClassifiers xsi:type="ecore:EClass" name="Publisher" eSuperTypes="#//NamespacedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="message" lowerBound="1"
        eType="#//TopicSpec"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Artifact">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="node" eType="#//Node" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SpecBase" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" unique="false" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="package" lowerBound="1"
        eType="#//Package" eOpposite="#//Package/spec"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fullname" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" changeable="false"
        volatile="true" transient="true" defaultValueLiteral="" unsettable="true"
        iD="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Subscriber" eSuperTypes="#//NamespacedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="message" lowerBound="1"
        eType="#//TopicSpec"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ServiceClient" eSuperTypes="#//NamespacedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="service" lowerBound="1"
        eType="#//ServiceSpec"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PackageSet">
    <eStructuralFeatures xsi:type="ecore:EReference" name="package" upperBound="-1"
        eType="#//Package" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActionSpec" eSuperTypes="#//SpecBase">
    <eStructuralFeatures xsi:type="ecore:EReference" name="goal" eType="#//MessageDefinition"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="result" eType="#//MessageDefinition"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="feedback" eType="#//MessageDefinition"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActionServer" eSuperTypes="#//NamespacedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="action" lowerBound="1"
        eType="#//ActionSpec"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActionClient" eSuperTypes="#//NamespacedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="action" lowerBound="1"
        eType="#//ActionSpec"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MessageDefinition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="MessagePart" upperBound="-1"
        eType="ecore:EClass PrimitivesTypes.ecore#//MessagePart" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Namespace" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="parts" unique="false" upperBound="-1"
        eType="#//GraphName"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GlobalNamespace" eSuperTypes="#//Namespace"/>
  <eClassifiers xsi:type="ecore:EClass" name="RelativeNamespace" eSuperTypes="#//Namespace"/>
  <eClassifiers xsi:type="ecore:EClass" name="PrivateNamespace" eSuperTypes="#//RelativeNamespace"/>
  <eClassifiers xsi:type="ecore:EClass" name="NamespacedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="namespace" eType="#//Namespace"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="#//GraphName"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="GraphName" instanceClassName="java.lang.String"/>
  <eClassifiers xsi:type="ecore:EClass" name="ParameterType" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="ParameterListType" eSuperTypes="#//ParameterType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sequence" upperBound="-1"
        eType="#//ParameterType" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="default" eType="#//ParameterSequence"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ParameterStructType" eSuperTypes="#//ParameterType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameterstructypetmember"
        upperBound="-1" eType="#//ParameterStructTypeMember" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ParameterIntegerType" eSuperTypes="#//ParameterType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="default" eType="#//ParameterInteger"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ParameterStringType" eSuperTypes="#//ParameterType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="default" eType="#//ParameterString"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ParameterDoubleType" eSuperTypes="#//ParameterType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="default" eType="#//ParameterDouble"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Parameter" eSuperTypes="#//NamespacedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//ParameterType"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//ParameterValue"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ParameterDateType" eSuperTypes="#//ParameterType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="default" eType="#//ParameterDate"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ParameterBooleanType" eSuperTypes="#//ParameterType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="default" eType="#//ParameterBoolean"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ParameterBase64Type" eSuperTypes="#//ParameterType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="default" eType="#//ParameterBase64"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ParameterAnyType" eSuperTypes="#//ParameterType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="default" eType="#//ParameterAny"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ParameterStructTypeMember">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//ParameterType"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="default" eType="#//ParameterStruct"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ParameterArrayType" eSuperTypes="#//ParameterType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//ParameterType"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="default" eType="#//ParameterSequence"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ParameterValue" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="ParameterAny" eSuperTypes="#//ParameterValue">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ParameterString" eSuperTypes="#//ParameterValue">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ParameterBase64" eSuperTypes="#//ParameterValue">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Base64Binary"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ParameterInteger" eSuperTypes="#//ParameterValue">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ParameterDouble" eSuperTypes="#//ParameterValue">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Double"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ParameterBoolean" eSuperTypes="#//ParameterValue">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Boolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ParameterSequence" eSuperTypes="#//ParameterValue">
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" upperBound="-1"
        eType="#//ParameterValue" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ParameterStruct" eSuperTypes="#//ParameterValue">
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" upperBound="-1"
        eType="#//ParameterStructMember" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ParameterStructMember">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" lowerBound="1" eType="#//ParameterValue"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ParameterDate" eSuperTypes="#//ParameterValue">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//DateTime"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AmentPackage" eSuperTypes="#//Package"/>
</ecore:EPackage>
