<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="rossystem" nsURI="http://www.ipa.fraunhofer.de/rossystem" nsPrefix="rossystem">
  <eClassifiers xsi:type="ecore:EClass" name="RosSystem">
    <eStructuralFeatures xsi:type="ecore:EReference" name="TopicConnections" upperBound="-1"
        eType="#//TopicConnection" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ServiceConnections" upperBound="-1"
        eType="#//ServiceConnection" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ActionConnections" upperBound="-1"
        eType="#//ActionConnection" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="RosComponent" upperBound="-1"
        eType="ecore:EClass ../../de.fraunhofer.ipa.componentInterface/model/componentInterface.ecore#//ComponentInterface"
        derived="true" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TopicConnection">
    <eStructuralFeatures xsi:type="ecore:EReference" name="From" lowerBound="1" upperBound="-1"
        eType="ecore:EClass ../../de.fraunhofer.ipa.componentInterface/model/componentInterface.ecore#//RosPublisher"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="To" lowerBound="1" upperBound="-1"
        eType="ecore:EClass ../../de.fraunhofer.ipa.componentInterface/model/componentInterface.ecore#//RosSubscriber"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="TopicName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ServiceConnection">
    <eStructuralFeatures xsi:type="ecore:EReference" name="From" lowerBound="1" upperBound="-1"
        eType="ecore:EClass ../../de.fraunhofer.ipa.componentInterface/model/componentInterface.ecore#//RosServiceServer"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="To" lowerBound="1" eType="ecore:EClass ../../de.fraunhofer.ipa.componentInterface/model/componentInterface.ecore#//RosServiceClient"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ServiceName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActionConnection">
    <eStructuralFeatures xsi:type="ecore:EReference" name="From" lowerBound="1" eType="ecore:EClass ../../de.fraunhofer.ipa.componentInterface/model/componentInterface.ecore#//RosActionServer"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="To" lowerBound="1" eType="ecore:EClass ../../de.fraunhofer.ipa.componentInterface/model/componentInterface.ecore#//RosActionClient"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ActionName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
