/*
 * generated by Xtext 2.25.0
 */
package de.fraunhofer.ipa.ros2;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class Ros2StandaloneSetup extends Ros2StandaloneSetupGenerated {

	public static void doSetup() {
		new Ros2StandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
