/*
 * generated by Xtext 2.25.0
 */
package de.fraunhofer.ipa.ros


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class BasicsStandaloneSetup extends BasicsStandaloneSetupGenerated {

    def static void doSetup() {
        new BasicsStandaloneSetup().createInjectorAndDoEMFRegistration()
    }
}
