<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="componentInterface" nsURI="http://www.ipa.fraunhofer.de/componentInterface"
    nsPrefix="componentInterface">
  <eClassifiers xsi:type="ecore:EClass" name="ComponentInterface" eSuperTypes="#//NameSpaceComponent">
    <eStructuralFeatures xsi:type="ecore:EReference" name="rospublisher" upperBound="-1"
        eType="#//RosPublisher" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rossubscriber" upperBound="-1"
        eType="#//RosSubscriber" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rosserviceserver" upperBound="-1"
        eType="#//RosServiceServer" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rosserviceclient" upperBound="-1"
        eType="#//RosServiceClient" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rosactionserver" upperBound="-1"
        eType="#//RosActionServer" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rosactionclient" upperBound="-1"
        eType="#//RosActionClient" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rosparameter" upperBound="-1"
        eType="#//RosParameter" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RosPublisher">
    <eStructuralFeatures xsi:type="ecore:EReference" name="publisher" eType="ecore:EClass ../../de.fraunhofer.ipa.ros/model/ros.ecore#//Publisher"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ns" eType="#//NS" defaultValueLiteral=""/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RosSubscriber">
    <eStructuralFeatures xsi:type="ecore:EReference" name="subscriber" eType="ecore:EClass ../../de.fraunhofer.ipa.ros/model/ros.ecore#//Subscriber"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ns" eType="#//NS"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RosServiceServer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="srvserver" eType="ecore:EClass ../../de.fraunhofer.ipa.ros/model/ros.ecore#//ServiceServer"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ns" eType="#//NS"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RosServiceClient">
    <eStructuralFeatures xsi:type="ecore:EReference" name="srvclient" eType="ecore:EClass ../../de.fraunhofer.ipa.ros/model/ros.ecore#//ServiceClient"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ns" eType="#//NS"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="NS" instanceClassName="java.lang.String"/>
  <eClassifiers xsi:type="ecore:EClass" name="NameSpaceComponent" abstract="true"
      interface="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="NameSpace" eType="#//NS"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RosActionServer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="actserver" eType="ecore:EClass ../../de.fraunhofer.ipa.ros/model/ros.ecore#//ActionServer"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ns" eType="#//NS"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RosActionClient">
    <eStructuralFeatures xsi:type="ecore:EReference" name="actclient" eType="ecore:EClass ../../de.fraunhofer.ipa.ros/model/ros.ecore#//ActionClient"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ns" eType="#//NS"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RosParameter">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameter" eType="ecore:EClass ../../de.fraunhofer.ipa.ros/model/ros.ecore#//Parameter"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ns" eType="#//NS" defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="ecore:EClass ../../de.fraunhofer.ipa.ros/model/ros.ecore#//ParameterValue"
        containment="true"/>
  </eClassifiers>
</ecore:EPackage>
