/**
 * generated by Xtext 2.12.0
 */
package de.fraunhofer.ipa.ros.ui;

import de.fraunhofer.ipa.ros.ui.AbstractRosArtifactUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class RosArtifactUiModule extends AbstractRosArtifactUiModule {
  public RosArtifactUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
