/*
 * generated by Xtext 2.20.0
 */
package de.fraunhofer.ipa.componentInterface.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractGrammarElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class ComponentInterfaceGrammarAccess extends AbstractGrammarElementFinder {
	
	public class ComponentInterfaceElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.fraunhofer.ipa.componentInterface.ComponentInterface.ComponentInterface");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cComponentInterfaceKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cNameKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cNameAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cNameEStringParserRuleCall_3_0 = (RuleCall)cNameAssignment_3.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cNameSpaceKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cNameSpaceAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cNameSpaceEStringParserRuleCall_4_1_0 = (RuleCall)cNameSpaceAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cRosPublishersKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		private final Assignment cRospublisherAssignment_5_2 = (Assignment)cGroup_5.eContents().get(2);
		private final RuleCall cRospublisherRosPublisherParserRuleCall_5_2_0 = (RuleCall)cRospublisherAssignment_5_2.eContents().get(0);
		private final Group cGroup_5_3 = (Group)cGroup_5.eContents().get(3);
		private final Keyword cCommaKeyword_5_3_0 = (Keyword)cGroup_5_3.eContents().get(0);
		private final Assignment cRospublisherAssignment_5_3_1 = (Assignment)cGroup_5_3.eContents().get(1);
		private final RuleCall cRospublisherRosPublisherParserRuleCall_5_3_1_0 = (RuleCall)cRospublisherAssignment_5_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5_4 = (Keyword)cGroup_5.eContents().get(4);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cRosSubscribersKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_6_1 = (Keyword)cGroup_6.eContents().get(1);
		private final Assignment cRossubscriberAssignment_6_2 = (Assignment)cGroup_6.eContents().get(2);
		private final RuleCall cRossubscriberRosSubscriberParserRuleCall_6_2_0 = (RuleCall)cRossubscriberAssignment_6_2.eContents().get(0);
		private final Group cGroup_6_3 = (Group)cGroup_6.eContents().get(3);
		private final Keyword cCommaKeyword_6_3_0 = (Keyword)cGroup_6_3.eContents().get(0);
		private final Assignment cRossubscriberAssignment_6_3_1 = (Assignment)cGroup_6_3.eContents().get(1);
		private final RuleCall cRossubscriberRosSubscriberParserRuleCall_6_3_1_0 = (RuleCall)cRossubscriberAssignment_6_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6_4 = (Keyword)cGroup_6.eContents().get(4);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cRosSrvServersKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_7_1 = (Keyword)cGroup_7.eContents().get(1);
		private final Assignment cRosserviceserverAssignment_7_2 = (Assignment)cGroup_7.eContents().get(2);
		private final RuleCall cRosserviceserverRosServiceServerParserRuleCall_7_2_0 = (RuleCall)cRosserviceserverAssignment_7_2.eContents().get(0);
		private final Group cGroup_7_3 = (Group)cGroup_7.eContents().get(3);
		private final Keyword cCommaKeyword_7_3_0 = (Keyword)cGroup_7_3.eContents().get(0);
		private final Assignment cRosserviceserverAssignment_7_3_1 = (Assignment)cGroup_7_3.eContents().get(1);
		private final RuleCall cRosserviceserverRosServiceServerParserRuleCall_7_3_1_0 = (RuleCall)cRosserviceserverAssignment_7_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7_4 = (Keyword)cGroup_7.eContents().get(4);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cRosSrvClientsKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_8_1 = (Keyword)cGroup_8.eContents().get(1);
		private final Assignment cRosserviceclientAssignment_8_2 = (Assignment)cGroup_8.eContents().get(2);
		private final RuleCall cRosserviceclientRosServiceClientParserRuleCall_8_2_0 = (RuleCall)cRosserviceclientAssignment_8_2.eContents().get(0);
		private final Group cGroup_8_3 = (Group)cGroup_8.eContents().get(3);
		private final Keyword cCommaKeyword_8_3_0 = (Keyword)cGroup_8_3.eContents().get(0);
		private final Assignment cRosserviceclientAssignment_8_3_1 = (Assignment)cGroup_8_3.eContents().get(1);
		private final RuleCall cRosserviceclientRosServiceClientParserRuleCall_8_3_1_0 = (RuleCall)cRosserviceclientAssignment_8_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_8_4 = (Keyword)cGroup_8.eContents().get(4);
		private final Group cGroup_9 = (Group)cGroup.eContents().get(9);
		private final Keyword cRosActionServersKeyword_9_0 = (Keyword)cGroup_9.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_9_1 = (Keyword)cGroup_9.eContents().get(1);
		private final Assignment cRosactionserverAssignment_9_2 = (Assignment)cGroup_9.eContents().get(2);
		private final RuleCall cRosactionserverRosActionServerParserRuleCall_9_2_0 = (RuleCall)cRosactionserverAssignment_9_2.eContents().get(0);
		private final Group cGroup_9_3 = (Group)cGroup_9.eContents().get(3);
		private final Keyword cCommaKeyword_9_3_0 = (Keyword)cGroup_9_3.eContents().get(0);
		private final Assignment cRosactionserverAssignment_9_3_1 = (Assignment)cGroup_9_3.eContents().get(1);
		private final RuleCall cRosactionserverRosActionServerParserRuleCall_9_3_1_0 = (RuleCall)cRosactionserverAssignment_9_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_9_4 = (Keyword)cGroup_9.eContents().get(4);
		private final Group cGroup_10 = (Group)cGroup.eContents().get(10);
		private final Keyword cRosActionClientsKeyword_10_0 = (Keyword)cGroup_10.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_10_1 = (Keyword)cGroup_10.eContents().get(1);
		private final Assignment cRosactionclientAssignment_10_2 = (Assignment)cGroup_10.eContents().get(2);
		private final RuleCall cRosactionclientRosActionClientParserRuleCall_10_2_0 = (RuleCall)cRosactionclientAssignment_10_2.eContents().get(0);
		private final Group cGroup_10_3 = (Group)cGroup_10.eContents().get(3);
		private final Keyword cCommaKeyword_10_3_0 = (Keyword)cGroup_10_3.eContents().get(0);
		private final Assignment cRosactionclientAssignment_10_3_1 = (Assignment)cGroup_10_3.eContents().get(1);
		private final RuleCall cRosactionclientRosActionClientParserRuleCall_10_3_1_0 = (RuleCall)cRosactionclientAssignment_10_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_10_4 = (Keyword)cGroup_10.eContents().get(4);
		private final Group cGroup_11 = (Group)cGroup.eContents().get(11);
		private final Keyword cRosParametersKeyword_11_0 = (Keyword)cGroup_11.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_11_1 = (Keyword)cGroup_11.eContents().get(1);
		private final Assignment cRosparameterAssignment_11_2 = (Assignment)cGroup_11.eContents().get(2);
		private final RuleCall cRosparameterRosParameterParserRuleCall_11_2_0 = (RuleCall)cRosparameterAssignment_11_2.eContents().get(0);
		private final Group cGroup_11_3 = (Group)cGroup_11.eContents().get(3);
		private final Keyword cCommaKeyword_11_3_0 = (Keyword)cGroup_11_3.eContents().get(0);
		private final Assignment cRosparameterAssignment_11_3_1 = (Assignment)cGroup_11_3.eContents().get(1);
		private final RuleCall cRosparameterRosParameterParserRuleCall_11_3_1_0 = (RuleCall)cRosparameterAssignment_11_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_11_4 = (Keyword)cGroup_11.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_12 = (Keyword)cGroup.eContents().get(12);
		
		//ComponentInterface:
		//	'ComponentInterface'
		//	'{'
		//	'name' name=EString ('NameSpace' NameSpace=EString)? ('RosPublishers' '{' rospublisher+=RosPublisher (","
		//	rospublisher+=RosPublisher)* '}')? ('RosSubscribers' '{' rossubscriber+=RosSubscriber (","
		//	rossubscriber+=RosSubscriber)* '}')? ('RosSrvServers' '{' rosserviceserver+=RosServiceServer (","
		//	rosserviceserver+=RosServiceServer)* '}')? ('RosSrvClients' '{' rosserviceclient+=RosServiceClient (","
		//	rosserviceclient+=RosServiceClient)* '}')? ('RosActionServers' '{' rosactionserver+=RosActionServer (","
		//	rosactionserver+=RosActionServer)* '}')? ('RosActionClients' '{' rosactionclient+=RosActionClient (","
		//	rosactionclient+=RosActionClient)* '}')? ('RosParameters' '{' rosparameter+=RosParameter (","
		//	rosparameter+=RosParameter)* '}')?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'ComponentInterface' '{' 'name' name=EString ('NameSpace' NameSpace=EString)? ('RosPublishers' '{'
		//rospublisher+=RosPublisher ("," rospublisher+=RosPublisher)* '}')? ('RosSubscribers' '{' rossubscriber+=RosSubscriber
		//("," rossubscriber+=RosSubscriber)* '}')? ('RosSrvServers' '{' rosserviceserver+=RosServiceServer (","
		//rosserviceserver+=RosServiceServer)* '}')? ('RosSrvClients' '{' rosserviceclient+=RosServiceClient (","
		//rosserviceclient+=RosServiceClient)* '}')? ('RosActionServers' '{' rosactionserver+=RosActionServer (","
		//rosactionserver+=RosActionServer)* '}')? ('RosActionClients' '{' rosactionclient+=RosActionClient (","
		//rosactionclient+=RosActionClient)* '}')? ('RosParameters' '{' rosparameter+=RosParameter (","
		//rosparameter+=RosParameter)* '}')? '}'
		public Group getGroup() { return cGroup; }
		
		//'ComponentInterface'
		public Keyword getComponentInterfaceKeyword_0() { return cComponentInterfaceKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//'name'
		public Keyword getNameKeyword_2() { return cNameKeyword_2; }
		
		//name=EString
		public Assignment getNameAssignment_3() { return cNameAssignment_3; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_3_0() { return cNameEStringParserRuleCall_3_0; }
		
		//('NameSpace' NameSpace=EString)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'NameSpace'
		public Keyword getNameSpaceKeyword_4_0() { return cNameSpaceKeyword_4_0; }
		
		//NameSpace=EString
		public Assignment getNameSpaceAssignment_4_1() { return cNameSpaceAssignment_4_1; }
		
		//EString
		public RuleCall getNameSpaceEStringParserRuleCall_4_1_0() { return cNameSpaceEStringParserRuleCall_4_1_0; }
		
		//('RosPublishers' '{' rospublisher+=RosPublisher ("," rospublisher+=RosPublisher)* '}')?
		public Group getGroup_5() { return cGroup_5; }
		
		//'RosPublishers'
		public Keyword getRosPublishersKeyword_5_0() { return cRosPublishersKeyword_5_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_5_1() { return cLeftCurlyBracketKeyword_5_1; }
		
		//rospublisher+=RosPublisher
		public Assignment getRospublisherAssignment_5_2() { return cRospublisherAssignment_5_2; }
		
		//RosPublisher
		public RuleCall getRospublisherRosPublisherParserRuleCall_5_2_0() { return cRospublisherRosPublisherParserRuleCall_5_2_0; }
		
		//("," rospublisher+=RosPublisher)*
		public Group getGroup_5_3() { return cGroup_5_3; }
		
		//","
		public Keyword getCommaKeyword_5_3_0() { return cCommaKeyword_5_3_0; }
		
		//rospublisher+=RosPublisher
		public Assignment getRospublisherAssignment_5_3_1() { return cRospublisherAssignment_5_3_1; }
		
		//RosPublisher
		public RuleCall getRospublisherRosPublisherParserRuleCall_5_3_1_0() { return cRospublisherRosPublisherParserRuleCall_5_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5_4() { return cRightCurlyBracketKeyword_5_4; }
		
		//('RosSubscribers' '{' rossubscriber+=RosSubscriber ("," rossubscriber+=RosSubscriber)* '}')?
		public Group getGroup_6() { return cGroup_6; }
		
		//'RosSubscribers'
		public Keyword getRosSubscribersKeyword_6_0() { return cRosSubscribersKeyword_6_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_6_1() { return cLeftCurlyBracketKeyword_6_1; }
		
		//rossubscriber+=RosSubscriber
		public Assignment getRossubscriberAssignment_6_2() { return cRossubscriberAssignment_6_2; }
		
		//RosSubscriber
		public RuleCall getRossubscriberRosSubscriberParserRuleCall_6_2_0() { return cRossubscriberRosSubscriberParserRuleCall_6_2_0; }
		
		//("," rossubscriber+=RosSubscriber)*
		public Group getGroup_6_3() { return cGroup_6_3; }
		
		//","
		public Keyword getCommaKeyword_6_3_0() { return cCommaKeyword_6_3_0; }
		
		//rossubscriber+=RosSubscriber
		public Assignment getRossubscriberAssignment_6_3_1() { return cRossubscriberAssignment_6_3_1; }
		
		//RosSubscriber
		public RuleCall getRossubscriberRosSubscriberParserRuleCall_6_3_1_0() { return cRossubscriberRosSubscriberParserRuleCall_6_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6_4() { return cRightCurlyBracketKeyword_6_4; }
		
		//('RosSrvServers' '{' rosserviceserver+=RosServiceServer ("," rosserviceserver+=RosServiceServer)* '}')?
		public Group getGroup_7() { return cGroup_7; }
		
		//'RosSrvServers'
		public Keyword getRosSrvServersKeyword_7_0() { return cRosSrvServersKeyword_7_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_7_1() { return cLeftCurlyBracketKeyword_7_1; }
		
		//rosserviceserver+=RosServiceServer
		public Assignment getRosserviceserverAssignment_7_2() { return cRosserviceserverAssignment_7_2; }
		
		//RosServiceServer
		public RuleCall getRosserviceserverRosServiceServerParserRuleCall_7_2_0() { return cRosserviceserverRosServiceServerParserRuleCall_7_2_0; }
		
		//("," rosserviceserver+=RosServiceServer)*
		public Group getGroup_7_3() { return cGroup_7_3; }
		
		//","
		public Keyword getCommaKeyword_7_3_0() { return cCommaKeyword_7_3_0; }
		
		//rosserviceserver+=RosServiceServer
		public Assignment getRosserviceserverAssignment_7_3_1() { return cRosserviceserverAssignment_7_3_1; }
		
		//RosServiceServer
		public RuleCall getRosserviceserverRosServiceServerParserRuleCall_7_3_1_0() { return cRosserviceserverRosServiceServerParserRuleCall_7_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7_4() { return cRightCurlyBracketKeyword_7_4; }
		
		//('RosSrvClients' '{' rosserviceclient+=RosServiceClient ("," rosserviceclient+=RosServiceClient)* '}')?
		public Group getGroup_8() { return cGroup_8; }
		
		//'RosSrvClients'
		public Keyword getRosSrvClientsKeyword_8_0() { return cRosSrvClientsKeyword_8_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_8_1() { return cLeftCurlyBracketKeyword_8_1; }
		
		//rosserviceclient+=RosServiceClient
		public Assignment getRosserviceclientAssignment_8_2() { return cRosserviceclientAssignment_8_2; }
		
		//RosServiceClient
		public RuleCall getRosserviceclientRosServiceClientParserRuleCall_8_2_0() { return cRosserviceclientRosServiceClientParserRuleCall_8_2_0; }
		
		//("," rosserviceclient+=RosServiceClient)*
		public Group getGroup_8_3() { return cGroup_8_3; }
		
		//","
		public Keyword getCommaKeyword_8_3_0() { return cCommaKeyword_8_3_0; }
		
		//rosserviceclient+=RosServiceClient
		public Assignment getRosserviceclientAssignment_8_3_1() { return cRosserviceclientAssignment_8_3_1; }
		
		//RosServiceClient
		public RuleCall getRosserviceclientRosServiceClientParserRuleCall_8_3_1_0() { return cRosserviceclientRosServiceClientParserRuleCall_8_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_8_4() { return cRightCurlyBracketKeyword_8_4; }
		
		//('RosActionServers' '{' rosactionserver+=RosActionServer ("," rosactionserver+=RosActionServer)* '}')?
		public Group getGroup_9() { return cGroup_9; }
		
		//'RosActionServers'
		public Keyword getRosActionServersKeyword_9_0() { return cRosActionServersKeyword_9_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_9_1() { return cLeftCurlyBracketKeyword_9_1; }
		
		//rosactionserver+=RosActionServer
		public Assignment getRosactionserverAssignment_9_2() { return cRosactionserverAssignment_9_2; }
		
		//RosActionServer
		public RuleCall getRosactionserverRosActionServerParserRuleCall_9_2_0() { return cRosactionserverRosActionServerParserRuleCall_9_2_0; }
		
		//("," rosactionserver+=RosActionServer)*
		public Group getGroup_9_3() { return cGroup_9_3; }
		
		//","
		public Keyword getCommaKeyword_9_3_0() { return cCommaKeyword_9_3_0; }
		
		//rosactionserver+=RosActionServer
		public Assignment getRosactionserverAssignment_9_3_1() { return cRosactionserverAssignment_9_3_1; }
		
		//RosActionServer
		public RuleCall getRosactionserverRosActionServerParserRuleCall_9_3_1_0() { return cRosactionserverRosActionServerParserRuleCall_9_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_9_4() { return cRightCurlyBracketKeyword_9_4; }
		
		//('RosActionClients' '{' rosactionclient+=RosActionClient ("," rosactionclient+=RosActionClient)* '}')?
		public Group getGroup_10() { return cGroup_10; }
		
		//'RosActionClients'
		public Keyword getRosActionClientsKeyword_10_0() { return cRosActionClientsKeyword_10_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_10_1() { return cLeftCurlyBracketKeyword_10_1; }
		
		//rosactionclient+=RosActionClient
		public Assignment getRosactionclientAssignment_10_2() { return cRosactionclientAssignment_10_2; }
		
		//RosActionClient
		public RuleCall getRosactionclientRosActionClientParserRuleCall_10_2_0() { return cRosactionclientRosActionClientParserRuleCall_10_2_0; }
		
		//("," rosactionclient+=RosActionClient)*
		public Group getGroup_10_3() { return cGroup_10_3; }
		
		//","
		public Keyword getCommaKeyword_10_3_0() { return cCommaKeyword_10_3_0; }
		
		//rosactionclient+=RosActionClient
		public Assignment getRosactionclientAssignment_10_3_1() { return cRosactionclientAssignment_10_3_1; }
		
		//RosActionClient
		public RuleCall getRosactionclientRosActionClientParserRuleCall_10_3_1_0() { return cRosactionclientRosActionClientParserRuleCall_10_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_10_4() { return cRightCurlyBracketKeyword_10_4; }
		
		//('RosParameters' '{' rosparameter+=RosParameter ("," rosparameter+=RosParameter)* '}')?
		public Group getGroup_11() { return cGroup_11; }
		
		//'RosParameters'
		public Keyword getRosParametersKeyword_11_0() { return cRosParametersKeyword_11_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_11_1() { return cLeftCurlyBracketKeyword_11_1; }
		
		//rosparameter+=RosParameter
		public Assignment getRosparameterAssignment_11_2() { return cRosparameterAssignment_11_2; }
		
		//RosParameter
		public RuleCall getRosparameterRosParameterParserRuleCall_11_2_0() { return cRosparameterRosParameterParserRuleCall_11_2_0; }
		
		//("," rosparameter+=RosParameter)*
		public Group getGroup_11_3() { return cGroup_11_3; }
		
		//","
		public Keyword getCommaKeyword_11_3_0() { return cCommaKeyword_11_3_0; }
		
		//rosparameter+=RosParameter
		public Assignment getRosparameterAssignment_11_3_1() { return cRosparameterAssignment_11_3_1; }
		
		//RosParameter
		public RuleCall getRosparameterRosParameterParserRuleCall_11_3_1_0() { return cRosparameterRosParameterParserRuleCall_11_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_11_4() { return cRightCurlyBracketKeyword_11_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_12() { return cRightCurlyBracketKeyword_12; }
	}
	public class RosPublisherElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.fraunhofer.ipa.componentInterface.ComponentInterface.RosPublisher");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cRosPublisherAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cRosPublisherKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cNsKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cNsAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cNsEStringParserRuleCall_4_1_0 = (RuleCall)cNsAssignment_4_1.eContents().get(0);
		private final Keyword cRefPublisherKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cPublisherAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final CrossReference cPublisherPublisherCrossReference_6_0 = (CrossReference)cPublisherAssignment_6.eContents().get(0);
		private final RuleCall cPublisherPublisherEStringParserRuleCall_6_0_1 = (RuleCall)cPublisherPublisherCrossReference_6_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//RosPublisher:
		//	{RosPublisher}
		//	'RosPublisher'
		//	name=EString?
		//	'{' ('ns' ns=EString)?
		//	'RefPublisher' publisher=[ros::Publisher|EString]
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{RosPublisher} 'RosPublisher' name=EString? '{' ('ns' ns=EString)? 'RefPublisher' publisher=[ros::Publisher|EString] '}'
		public Group getGroup() { return cGroup; }
		
		//{RosPublisher}
		public Action getRosPublisherAction_0() { return cRosPublisherAction_0; }
		
		//'RosPublisher'
		public Keyword getRosPublisherKeyword_1() { return cRosPublisherKeyword_1; }
		
		//name=EString?
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('ns' ns=EString)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'ns'
		public Keyword getNsKeyword_4_0() { return cNsKeyword_4_0; }
		
		//ns=EString
		public Assignment getNsAssignment_4_1() { return cNsAssignment_4_1; }
		
		//EString
		public RuleCall getNsEStringParserRuleCall_4_1_0() { return cNsEStringParserRuleCall_4_1_0; }
		
		//'RefPublisher'
		public Keyword getRefPublisherKeyword_5() { return cRefPublisherKeyword_5; }
		
		//publisher=[ros::Publisher|EString]
		public Assignment getPublisherAssignment_6() { return cPublisherAssignment_6; }
		
		//[ros::Publisher|EString]
		public CrossReference getPublisherPublisherCrossReference_6_0() { return cPublisherPublisherCrossReference_6_0; }
		
		//EString
		public RuleCall getPublisherPublisherEStringParserRuleCall_6_0_1() { return cPublisherPublisherEStringParserRuleCall_6_0_1; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}
	public class RosSubscriberElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.fraunhofer.ipa.componentInterface.ComponentInterface.RosSubscriber");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cRosSubscriberAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cRosSubscriberKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cNsKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cNsAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cNsEStringParserRuleCall_4_1_0 = (RuleCall)cNsAssignment_4_1.eContents().get(0);
		private final Keyword cRefSubscriberKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cSubscriberAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final CrossReference cSubscriberSubscriberCrossReference_6_0 = (CrossReference)cSubscriberAssignment_6.eContents().get(0);
		private final RuleCall cSubscriberSubscriberEStringParserRuleCall_6_0_1 = (RuleCall)cSubscriberSubscriberCrossReference_6_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//RosSubscriber:
		//	{RosSubscriber}
		//	'RosSubscriber'
		//	name=EString?
		//	'{' ('ns' ns=EString)?
		//	'RefSubscriber' subscriber=[ros::Subscriber|EString]
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{RosSubscriber} 'RosSubscriber' name=EString? '{' ('ns' ns=EString)? 'RefSubscriber'
		//subscriber=[ros::Subscriber|EString] '}'
		public Group getGroup() { return cGroup; }
		
		//{RosSubscriber}
		public Action getRosSubscriberAction_0() { return cRosSubscriberAction_0; }
		
		//'RosSubscriber'
		public Keyword getRosSubscriberKeyword_1() { return cRosSubscriberKeyword_1; }
		
		//name=EString?
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('ns' ns=EString)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'ns'
		public Keyword getNsKeyword_4_0() { return cNsKeyword_4_0; }
		
		//ns=EString
		public Assignment getNsAssignment_4_1() { return cNsAssignment_4_1; }
		
		//EString
		public RuleCall getNsEStringParserRuleCall_4_1_0() { return cNsEStringParserRuleCall_4_1_0; }
		
		//'RefSubscriber'
		public Keyword getRefSubscriberKeyword_5() { return cRefSubscriberKeyword_5; }
		
		//subscriber=[ros::Subscriber|EString]
		public Assignment getSubscriberAssignment_6() { return cSubscriberAssignment_6; }
		
		//[ros::Subscriber|EString]
		public CrossReference getSubscriberSubscriberCrossReference_6_0() { return cSubscriberSubscriberCrossReference_6_0; }
		
		//EString
		public RuleCall getSubscriberSubscriberEStringParserRuleCall_6_0_1() { return cSubscriberSubscriberEStringParserRuleCall_6_0_1; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}
	public class RosServiceServerElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.fraunhofer.ipa.componentInterface.ComponentInterface.RosServiceServer");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cRosServiceServerAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cRosServiceServerKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cNsKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cNsAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cNsEStringParserRuleCall_4_1_0 = (RuleCall)cNsAssignment_4_1.eContents().get(0);
		private final Keyword cRefServerKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cSrvserverAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final CrossReference cSrvserverServiceServerCrossReference_6_0 = (CrossReference)cSrvserverAssignment_6.eContents().get(0);
		private final RuleCall cSrvserverServiceServerEStringParserRuleCall_6_0_1 = (RuleCall)cSrvserverServiceServerCrossReference_6_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//RosServiceServer:
		//	{RosServiceServer}
		//	'RosServiceServer'
		//	name=EString?
		//	'{' ('ns' ns=EString)?
		//	'RefServer' srvserver=[ros::ServiceServer|EString]
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{RosServiceServer} 'RosServiceServer' name=EString? '{' ('ns' ns=EString)? 'RefServer'
		//srvserver=[ros::ServiceServer|EString] '}'
		public Group getGroup() { return cGroup; }
		
		//{RosServiceServer}
		public Action getRosServiceServerAction_0() { return cRosServiceServerAction_0; }
		
		//'RosServiceServer'
		public Keyword getRosServiceServerKeyword_1() { return cRosServiceServerKeyword_1; }
		
		//name=EString?
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('ns' ns=EString)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'ns'
		public Keyword getNsKeyword_4_0() { return cNsKeyword_4_0; }
		
		//ns=EString
		public Assignment getNsAssignment_4_1() { return cNsAssignment_4_1; }
		
		//EString
		public RuleCall getNsEStringParserRuleCall_4_1_0() { return cNsEStringParserRuleCall_4_1_0; }
		
		//'RefServer'
		public Keyword getRefServerKeyword_5() { return cRefServerKeyword_5; }
		
		//srvserver=[ros::ServiceServer|EString]
		public Assignment getSrvserverAssignment_6() { return cSrvserverAssignment_6; }
		
		//[ros::ServiceServer|EString]
		public CrossReference getSrvserverServiceServerCrossReference_6_0() { return cSrvserverServiceServerCrossReference_6_0; }
		
		//EString
		public RuleCall getSrvserverServiceServerEStringParserRuleCall_6_0_1() { return cSrvserverServiceServerEStringParserRuleCall_6_0_1; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}
	public class RosServiceClientElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.fraunhofer.ipa.componentInterface.ComponentInterface.RosServiceClient");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cRosServiceClientAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cRosServiceClientKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cNsKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cNsAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cNsEStringParserRuleCall_4_1_0 = (RuleCall)cNsAssignment_4_1.eContents().get(0);
		private final Keyword cRefClientKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cSrvclientAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final CrossReference cSrvclientServiceClientCrossReference_6_0 = (CrossReference)cSrvclientAssignment_6.eContents().get(0);
		private final RuleCall cSrvclientServiceClientEStringParserRuleCall_6_0_1 = (RuleCall)cSrvclientServiceClientCrossReference_6_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//RosServiceClient:
		//	{RosServiceClient}
		//	'RosServiceClient'
		//	name=EString?
		//	'{' ('ns' ns=EString)?
		//	'RefClient' srvclient=[ros::ServiceClient|EString]
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{RosServiceClient} 'RosServiceClient' name=EString? '{' ('ns' ns=EString)? 'RefClient'
		//srvclient=[ros::ServiceClient|EString] '}'
		public Group getGroup() { return cGroup; }
		
		//{RosServiceClient}
		public Action getRosServiceClientAction_0() { return cRosServiceClientAction_0; }
		
		//'RosServiceClient'
		public Keyword getRosServiceClientKeyword_1() { return cRosServiceClientKeyword_1; }
		
		//name=EString?
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('ns' ns=EString)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'ns'
		public Keyword getNsKeyword_4_0() { return cNsKeyword_4_0; }
		
		//ns=EString
		public Assignment getNsAssignment_4_1() { return cNsAssignment_4_1; }
		
		//EString
		public RuleCall getNsEStringParserRuleCall_4_1_0() { return cNsEStringParserRuleCall_4_1_0; }
		
		//'RefClient'
		public Keyword getRefClientKeyword_5() { return cRefClientKeyword_5; }
		
		//srvclient=[ros::ServiceClient|EString]
		public Assignment getSrvclientAssignment_6() { return cSrvclientAssignment_6; }
		
		//[ros::ServiceClient|EString]
		public CrossReference getSrvclientServiceClientCrossReference_6_0() { return cSrvclientServiceClientCrossReference_6_0; }
		
		//EString
		public RuleCall getSrvclientServiceClientEStringParserRuleCall_6_0_1() { return cSrvclientServiceClientEStringParserRuleCall_6_0_1; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}
	public class RosActionServerElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.fraunhofer.ipa.componentInterface.ComponentInterface.RosActionServer");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cRosActionServerAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cRosActionServerKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cNsKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cNsAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cNsEStringParserRuleCall_4_1_0 = (RuleCall)cNsAssignment_4_1.eContents().get(0);
		private final Keyword cRefServerKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cActserverAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final CrossReference cActserverActionServerCrossReference_6_0 = (CrossReference)cActserverAssignment_6.eContents().get(0);
		private final RuleCall cActserverActionServerEStringParserRuleCall_6_0_1 = (RuleCall)cActserverActionServerCrossReference_6_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//RosActionServer:
		//	{RosActionServer}
		//	'RosActionServer'
		//	name=EString?
		//	'{' ('ns' ns=EString)?
		//	'RefServer' actserver=[ros::ActionServer|EString]
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{RosActionServer} 'RosActionServer' name=EString? '{' ('ns' ns=EString)? 'RefServer'
		//actserver=[ros::ActionServer|EString] '}'
		public Group getGroup() { return cGroup; }
		
		//{RosActionServer}
		public Action getRosActionServerAction_0() { return cRosActionServerAction_0; }
		
		//'RosActionServer'
		public Keyword getRosActionServerKeyword_1() { return cRosActionServerKeyword_1; }
		
		//name=EString?
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('ns' ns=EString)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'ns'
		public Keyword getNsKeyword_4_0() { return cNsKeyword_4_0; }
		
		//ns=EString
		public Assignment getNsAssignment_4_1() { return cNsAssignment_4_1; }
		
		//EString
		public RuleCall getNsEStringParserRuleCall_4_1_0() { return cNsEStringParserRuleCall_4_1_0; }
		
		//'RefServer'
		public Keyword getRefServerKeyword_5() { return cRefServerKeyword_5; }
		
		//actserver=[ros::ActionServer|EString]
		public Assignment getActserverAssignment_6() { return cActserverAssignment_6; }
		
		//[ros::ActionServer|EString]
		public CrossReference getActserverActionServerCrossReference_6_0() { return cActserverActionServerCrossReference_6_0; }
		
		//EString
		public RuleCall getActserverActionServerEStringParserRuleCall_6_0_1() { return cActserverActionServerEStringParserRuleCall_6_0_1; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}
	public class RosActionClientElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.fraunhofer.ipa.componentInterface.ComponentInterface.RosActionClient");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cRosActionClientAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cRosActionClientKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cNsKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cNsAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cNsEStringParserRuleCall_4_1_0 = (RuleCall)cNsAssignment_4_1.eContents().get(0);
		private final Keyword cRefClientKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cActclientAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final CrossReference cActclientActionClientCrossReference_6_0 = (CrossReference)cActclientAssignment_6.eContents().get(0);
		private final RuleCall cActclientActionClientEStringParserRuleCall_6_0_1 = (RuleCall)cActclientActionClientCrossReference_6_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//RosActionClient:
		//	{RosActionClient}
		//	'RosActionClient'
		//	name=EString?
		//	'{' ('ns' ns=EString)?
		//	'RefClient' actclient=[ros::ActionClient|EString]
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{RosActionClient} 'RosActionClient' name=EString? '{' ('ns' ns=EString)? 'RefClient'
		//actclient=[ros::ActionClient|EString] '}'
		public Group getGroup() { return cGroup; }
		
		//{RosActionClient}
		public Action getRosActionClientAction_0() { return cRosActionClientAction_0; }
		
		//'RosActionClient'
		public Keyword getRosActionClientKeyword_1() { return cRosActionClientKeyword_1; }
		
		//name=EString?
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('ns' ns=EString)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'ns'
		public Keyword getNsKeyword_4_0() { return cNsKeyword_4_0; }
		
		//ns=EString
		public Assignment getNsAssignment_4_1() { return cNsAssignment_4_1; }
		
		//EString
		public RuleCall getNsEStringParserRuleCall_4_1_0() { return cNsEStringParserRuleCall_4_1_0; }
		
		//'RefClient'
		public Keyword getRefClientKeyword_5() { return cRefClientKeyword_5; }
		
		//actclient=[ros::ActionClient|EString]
		public Assignment getActclientAssignment_6() { return cActclientAssignment_6; }
		
		//[ros::ActionClient|EString]
		public CrossReference getActclientActionClientCrossReference_6_0() { return cActclientActionClientCrossReference_6_0; }
		
		//EString
		public RuleCall getActclientActionClientEStringParserRuleCall_6_0_1() { return cActclientActionClientEStringParserRuleCall_6_0_1; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}
	public class RosParameterElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.fraunhofer.ipa.componentInterface.ComponentInterface.RosParameter");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cRosParameterAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cRosParameterKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cNsKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cNsAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cNsEStringParserRuleCall_4_1_0 = (RuleCall)cNsAssignment_4_1.eContents().get(0);
		private final Keyword cRefParameterKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cParameterAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final CrossReference cParameterParameterCrossReference_6_0 = (CrossReference)cParameterAssignment_6.eContents().get(0);
		private final RuleCall cParameterParameterEStringParserRuleCall_6_0_1 = (RuleCall)cParameterParameterCrossReference_6_0.eContents().get(1);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cValueKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cValueAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final RuleCall cValueParameterValueParserRuleCall_7_1_0 = (RuleCall)cValueAssignment_7_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		
		//RosParameter:
		//	{RosParameter}
		//	'RosParameter'
		//	name=EString?
		//	'{' ('ns' ns=EString)?
		//	'RefParameter' parameter=[ros::Parameter|EString] ('value' value=ParameterValue)?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{RosParameter} 'RosParameter' name=EString? '{' ('ns' ns=EString)? 'RefParameter' parameter=[ros::Parameter|EString]
		//('value' value=ParameterValue)? '}'
		public Group getGroup() { return cGroup; }
		
		//{RosParameter}
		public Action getRosParameterAction_0() { return cRosParameterAction_0; }
		
		//'RosParameter'
		public Keyword getRosParameterKeyword_1() { return cRosParameterKeyword_1; }
		
		//name=EString?
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('ns' ns=EString)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'ns'
		public Keyword getNsKeyword_4_0() { return cNsKeyword_4_0; }
		
		//ns=EString
		public Assignment getNsAssignment_4_1() { return cNsAssignment_4_1; }
		
		//EString
		public RuleCall getNsEStringParserRuleCall_4_1_0() { return cNsEStringParserRuleCall_4_1_0; }
		
		//'RefParameter'
		public Keyword getRefParameterKeyword_5() { return cRefParameterKeyword_5; }
		
		//parameter=[ros::Parameter|EString]
		public Assignment getParameterAssignment_6() { return cParameterAssignment_6; }
		
		//[ros::Parameter|EString]
		public CrossReference getParameterParameterCrossReference_6_0() { return cParameterParameterCrossReference_6_0; }
		
		//EString
		public RuleCall getParameterParameterEStringParserRuleCall_6_0_1() { return cParameterParameterEStringParserRuleCall_6_0_1; }
		
		//('value' value=ParameterValue)?
		public Group getGroup_7() { return cGroup_7; }
		
		//'value'
		public Keyword getValueKeyword_7_0() { return cValueKeyword_7_0; }
		
		//value=ParameterValue
		public Assignment getValueAssignment_7_1() { return cValueAssignment_7_1; }
		
		//ParameterValue
		public RuleCall getValueParameterValueParserRuleCall_7_1_0() { return cValueParameterValueParserRuleCall_7_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
	}
	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.fraunhofer.ipa.componentInterface.ComponentInterface.EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString:
		//	STRING | ID;
		@Override public ParserRule getRule() { return rule; }
		
		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}
	public class NSElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.fraunhofer.ipa.componentInterface.ComponentInterface.NS");
		private final Keyword cNSKeyword = (Keyword)rule.eContents().get(1);
		
		//NS NS:
		//	'NS' /* TODO: implement this rule and an appropriate IValueConverter */;
		@Override public ParserRule getRule() { return rule; }
		
		//'NS'
		public Keyword getNSKeyword() { return cNSKeyword; }
	}
	public class ParameterValueElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.fraunhofer.ipa.componentInterface.ComponentInterface.ParameterValue");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cParameterDoubleParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cParameterBooleanParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cParameterIntegerParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cParameterBase64ParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		private final RuleCall cParameterListParserRuleCall_4 = (RuleCall)cAlternatives.eContents().get(4);
		private final RuleCall cParameterStructParserRuleCall_5 = (RuleCall)cAlternatives.eContents().get(5);
		private final RuleCall cParameterStringParserRuleCall_6 = (RuleCall)cAlternatives.eContents().get(6);
		
		//// PARAMETERS!!
		//ParameterValue ros::ParameterValue:
		//	ParameterDouble | ParameterBoolean | ParameterInteger | ParameterBase64 | ParameterList | ParameterStruct |
		//	ParameterString;
		@Override public ParserRule getRule() { return rule; }
		
		//ParameterDouble | ParameterBoolean | ParameterInteger | ParameterBase64 | ParameterList | ParameterStruct |
		//ParameterString
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//ParameterDouble
		public RuleCall getParameterDoubleParserRuleCall_0() { return cParameterDoubleParserRuleCall_0; }
		
		//ParameterBoolean
		public RuleCall getParameterBooleanParserRuleCall_1() { return cParameterBooleanParserRuleCall_1; }
		
		//ParameterInteger
		public RuleCall getParameterIntegerParserRuleCall_2() { return cParameterIntegerParserRuleCall_2; }
		
		//ParameterBase64
		public RuleCall getParameterBase64ParserRuleCall_3() { return cParameterBase64ParserRuleCall_3; }
		
		//ParameterList
		public RuleCall getParameterListParserRuleCall_4() { return cParameterListParserRuleCall_4; }
		
		//ParameterStruct
		public RuleCall getParameterStructParserRuleCall_5() { return cParameterStructParserRuleCall_5; }
		
		//ParameterString
		public RuleCall getParameterStringParserRuleCall_6() { return cParameterStringParserRuleCall_6; }
	}
	public class ParameterStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.fraunhofer.ipa.componentInterface.ComponentInterface.ParameterString");
		private final Assignment cValueAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cValueEStringParserRuleCall_0 = (RuleCall)cValueAssignment.eContents().get(0);
		
		//ParameterString ros::ParameterString:
		//	value=EString;
		@Override public ParserRule getRule() { return rule; }
		
		//value=EString
		public Assignment getValueAssignment() { return cValueAssignment; }
		
		//EString
		public RuleCall getValueEStringParserRuleCall_0() { return cValueEStringParserRuleCall_0; }
	}
	public class ParameterBase64Elements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.fraunhofer.ipa.componentInterface.ComponentInterface.ParameterBase64");
		private final Assignment cValueAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cValueBase64BinaryParserRuleCall_0 = (RuleCall)cValueAssignment.eContents().get(0);
		
		//ParameterBase64 ros::ParameterBase64:
		//	value=Base64Binary;
		@Override public ParserRule getRule() { return rule; }
		
		//value=Base64Binary
		public Assignment getValueAssignment() { return cValueAssignment; }
		
		//Base64Binary
		public RuleCall getValueBase64BinaryParserRuleCall_0() { return cValueBase64BinaryParserRuleCall_0; }
	}
	public class ParameterIntegerElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.fraunhofer.ipa.componentInterface.ComponentInterface.ParameterInteger");
		private final Assignment cValueAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cValueInteger0ParserRuleCall_0 = (RuleCall)cValueAssignment.eContents().get(0);
		
		//ParameterInteger ros::ParameterInteger:
		//	value=Integer0;
		@Override public ParserRule getRule() { return rule; }
		
		//value=Integer0
		public Assignment getValueAssignment() { return cValueAssignment; }
		
		//Integer0
		public RuleCall getValueInteger0ParserRuleCall_0() { return cValueInteger0ParserRuleCall_0; }
	}
	public class ParameterDoubleElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.fraunhofer.ipa.componentInterface.ComponentInterface.ParameterDouble");
		private final Assignment cValueAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cValueDouble0ParserRuleCall_0 = (RuleCall)cValueAssignment.eContents().get(0);
		
		//ParameterDouble ros::ParameterDouble:
		//	value=Double0;
		@Override public ParserRule getRule() { return rule; }
		
		//value=Double0
		public Assignment getValueAssignment() { return cValueAssignment; }
		
		//Double0
		public RuleCall getValueDouble0ParserRuleCall_0() { return cValueDouble0ParserRuleCall_0; }
	}
	public class ParameterBooleanElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.fraunhofer.ipa.componentInterface.ComponentInterface.ParameterBoolean");
		private final Assignment cValueAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cValueBoolean0ParserRuleCall_0 = (RuleCall)cValueAssignment.eContents().get(0);
		
		//ParameterBoolean ros::ParameterBoolean:
		//	value=boolean0;
		@Override public ParserRule getRule() { return rule; }
		
		//value=boolean0
		public Assignment getValueAssignment() { return cValueAssignment; }
		
		//boolean0
		public RuleCall getValueBoolean0ParserRuleCall_0() { return cValueBoolean0ParserRuleCall_0; }
	}
	public class ParameterListElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.fraunhofer.ipa.componentInterface.ComponentInterface.ParameterList");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cParameterSequenceAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cValueAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cValueParameterValueParserRuleCall_2_0 = (RuleCall)cValueAssignment_2.eContents().get(0);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cCommaKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cValueAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cValueParameterValueParserRuleCall_3_1_0 = (RuleCall)cValueAssignment_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//ParameterList ros::ParameterSequence:
		//	{ros::ParameterSequence}
		//	'{' value+=ParameterValue (',' value+=ParameterValue)* '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{ros::ParameterSequence} '{' value+=ParameterValue (',' value+=ParameterValue)* '}'
		public Group getGroup() { return cGroup; }
		
		//{ros::ParameterSequence}
		public Action getParameterSequenceAction_0() { return cParameterSequenceAction_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//value+=ParameterValue
		public Assignment getValueAssignment_2() { return cValueAssignment_2; }
		
		//ParameterValue
		public RuleCall getValueParameterValueParserRuleCall_2_0() { return cValueParameterValueParserRuleCall_2_0; }
		
		//(',' value+=ParameterValue)*
		public Group getGroup_3() { return cGroup_3; }
		
		//','
		public Keyword getCommaKeyword_3_0() { return cCommaKeyword_3_0; }
		
		//value+=ParameterValue
		public Assignment getValueAssignment_3_1() { return cValueAssignment_3_1; }
		
		//ParameterValue
		public RuleCall getValueParameterValueParserRuleCall_3_1_0() { return cValueParameterValueParserRuleCall_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	public class ParameterArrayElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.fraunhofer.ipa.componentInterface.ComponentInterface.ParameterArray");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cParameterSequenceAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cValueAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cValueParameterValueParserRuleCall_2_0 = (RuleCall)cValueAssignment_2.eContents().get(0);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cCommaKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cValueAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cValueParameterValueParserRuleCall_3_1_0 = (RuleCall)cValueAssignment_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//ParameterArray ros::ParameterSequence:
		//	{ros::ParameterSequence}
		//	'{' value+=ParameterValue (',' value+=ParameterValue)* '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{ros::ParameterSequence} '{' value+=ParameterValue (',' value+=ParameterValue)* '}'
		public Group getGroup() { return cGroup; }
		
		//{ros::ParameterSequence}
		public Action getParameterSequenceAction_0() { return cParameterSequenceAction_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//value+=ParameterValue
		public Assignment getValueAssignment_2() { return cValueAssignment_2; }
		
		//ParameterValue
		public RuleCall getValueParameterValueParserRuleCall_2_0() { return cValueParameterValueParserRuleCall_2_0; }
		
		//(',' value+=ParameterValue)*
		public Group getGroup_3() { return cGroup_3; }
		
		//','
		public Keyword getCommaKeyword_3_0() { return cCommaKeyword_3_0; }
		
		//value+=ParameterValue
		public Assignment getValueAssignment_3_1() { return cValueAssignment_3_1; }
		
		//ParameterValue
		public RuleCall getValueParameterValueParserRuleCall_3_1_0() { return cValueParameterValueParserRuleCall_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	public class ParameterStructElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.fraunhofer.ipa.componentInterface.ComponentInterface.ParameterStruct");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cParameterStructAction_0 = (Action)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final Assignment cValueAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cValueParameterStructMemberParserRuleCall_1_1_0 = (RuleCall)cValueAssignment_1_1.eContents().get(0);
		private final Group cGroup_1_2 = (Group)cGroup_1.eContents().get(2);
		private final Keyword cCommaKeyword_1_2_0 = (Keyword)cGroup_1_2.eContents().get(0);
		private final Assignment cValueAssignment_1_2_1 = (Assignment)cGroup_1_2.eContents().get(1);
		private final RuleCall cValueParameterStructMemberParserRuleCall_1_2_1_0 = (RuleCall)cValueAssignment_1_2_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_1_3 = (Keyword)cGroup_1.eContents().get(3);
		
		//ParameterStruct ros::ParameterStruct:
		//	{ros::ParameterStruct} ('{' value+=ParameterStructMember ("," value+=ParameterStructMember)* '}')?;
		@Override public ParserRule getRule() { return rule; }
		
		//{ros::ParameterStruct} ('{' value+=ParameterStructMember ("," value+=ParameterStructMember)* '}')?
		public Group getGroup() { return cGroup; }
		
		//{ros::ParameterStruct}
		public Action getParameterStructAction_0() { return cParameterStructAction_0; }
		
		//('{' value+=ParameterStructMember ("," value+=ParameterStructMember)* '}')?
		public Group getGroup_1() { return cGroup_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1_0() { return cLeftCurlyBracketKeyword_1_0; }
		
		//value+=ParameterStructMember
		public Assignment getValueAssignment_1_1() { return cValueAssignment_1_1; }
		
		//ParameterStructMember
		public RuleCall getValueParameterStructMemberParserRuleCall_1_1_0() { return cValueParameterStructMemberParserRuleCall_1_1_0; }
		
		//("," value+=ParameterStructMember)*
		public Group getGroup_1_2() { return cGroup_1_2; }
		
		//","
		public Keyword getCommaKeyword_1_2_0() { return cCommaKeyword_1_2_0; }
		
		//value+=ParameterStructMember
		public Assignment getValueAssignment_1_2_1() { return cValueAssignment_1_2_1; }
		
		//ParameterStructMember
		public RuleCall getValueParameterStructMemberParserRuleCall_1_2_1_0() { return cValueParameterStructMemberParserRuleCall_1_2_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_1_3() { return cRightCurlyBracketKeyword_1_3; }
	}
	public class ParameterStructMemberElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.fraunhofer.ipa.componentInterface.ComponentInterface.ParameterStructMember");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cNameEStringParserRuleCall_0_0 = (RuleCall)cNameAssignment_0.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cValueKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cValueAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cValueParameterValueParserRuleCall_3_0 = (RuleCall)cValueAssignment_3.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//ParameterStructMember ros::ParameterStructMember:
		//	name=EString
		//	'{'
		//	'value' value=ParameterValue
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//name=EString '{' 'value' value=ParameterValue '}'
		public Group getGroup() { return cGroup; }
		
		//name=EString
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_0_0() { return cNameEStringParserRuleCall_0_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//'value'
		public Keyword getValueKeyword_2() { return cValueKeyword_2; }
		
		//value=ParameterValue
		public Assignment getValueAssignment_3() { return cValueAssignment_3; }
		
		//ParameterValue
		public RuleCall getValueParameterValueParserRuleCall_3_0() { return cValueParameterValueParserRuleCall_3_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	public class Base64BinaryElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.fraunhofer.ipa.componentInterface.ComponentInterface.Base64Binary");
		private final RuleCall cBINARYTerminalRuleCall = (RuleCall)rule.eContents().get(1);
		
		//Base64Binary type::Base64Binary:
		//	BINARY;
		@Override public ParserRule getRule() { return rule; }
		
		//BINARY
		public RuleCall getBINARYTerminalRuleCall() { return cBINARYTerminalRuleCall; }
	}
	public class Boolean0Elements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.fraunhofer.ipa.componentInterface.ComponentInterface.boolean0");
		private final RuleCall cBOOLEANTerminalRuleCall = (RuleCall)rule.eContents().get(1);
		
		//boolean0 type::Boolean:
		//	BOOLEAN;
		@Override public ParserRule getRule() { return rule; }
		
		//BOOLEAN
		public RuleCall getBOOLEANTerminalRuleCall() { return cBOOLEANTerminalRuleCall; }
	}
	public class Double0Elements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.fraunhofer.ipa.componentInterface.ComponentInterface.Double0");
		private final RuleCall cDOUBLETerminalRuleCall = (RuleCall)rule.eContents().get(1);
		
		//Double0 type::Double:
		//	DOUBLE;
		@Override public ParserRule getRule() { return rule; }
		
		//DOUBLE
		public RuleCall getDOUBLETerminalRuleCall() { return cDOUBLETerminalRuleCall; }
	}
	public class Integer0Elements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.fraunhofer.ipa.componentInterface.ComponentInterface.Integer0");
		private final RuleCall cDECINTTerminalRuleCall = (RuleCall)rule.eContents().get(1);
		
		//Integer0 type::Int:
		//	DECINT;
		@Override public ParserRule getRule() { return rule; }
		
		//DECINT
		public RuleCall getDECINTTerminalRuleCall() { return cDECINTTerminalRuleCall; }
	}
	public class DateTime0Elements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.fraunhofer.ipa.componentInterface.ComponentInterface.DateTime0");
		private final RuleCall cDATE_TIMETerminalRuleCall = (RuleCall)rule.eContents().get(1);
		
		//DateTime0 type::DateTime:
		//	DATE_TIME;
		@Override public ParserRule getRule() { return rule; }
		
		//DATE_TIME
		public RuleCall getDATE_TIMETerminalRuleCall() { return cDATE_TIMETerminalRuleCall; }
	}
	
	
	private final ComponentInterfaceElements pComponentInterface;
	private final RosPublisherElements pRosPublisher;
	private final RosSubscriberElements pRosSubscriber;
	private final RosServiceServerElements pRosServiceServer;
	private final RosServiceClientElements pRosServiceClient;
	private final RosActionServerElements pRosActionServer;
	private final RosActionClientElements pRosActionClient;
	private final RosParameterElements pRosParameter;
	private final EStringElements pEString;
	private final NSElements pNS;
	private final ParameterValueElements pParameterValue;
	private final ParameterStringElements pParameterString;
	private final ParameterBase64Elements pParameterBase64;
	private final ParameterIntegerElements pParameterInteger;
	private final ParameterDoubleElements pParameterDouble;
	private final ParameterBooleanElements pParameterBoolean;
	private final ParameterListElements pParameterList;
	private final ParameterArrayElements pParameterArray;
	private final ParameterStructElements pParameterStruct;
	private final ParameterStructMemberElements pParameterStructMember;
	private final TerminalRule tDIGIT;
	private final TerminalRule tBINARY;
	private final TerminalRule tBOOLEAN;
	private final TerminalRule tDOUBLE;
	private final TerminalRule tDECINT;
	private final TerminalRule tDAY;
	private final TerminalRule tMONTH;
	private final TerminalRule tYEAR;
	private final TerminalRule tHOUR;
	private final TerminalRule tMIN_SEC;
	private final TerminalRule tDATE_TIME;
	private final Base64BinaryElements pBase64Binary;
	private final Boolean0Elements pBoolean0;
	private final Double0Elements pDouble0;
	private final Integer0Elements pInteger0;
	private final DateTime0Elements pDateTime0;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public ComponentInterfaceGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pComponentInterface = new ComponentInterfaceElements();
		this.pRosPublisher = new RosPublisherElements();
		this.pRosSubscriber = new RosSubscriberElements();
		this.pRosServiceServer = new RosServiceServerElements();
		this.pRosServiceClient = new RosServiceClientElements();
		this.pRosActionServer = new RosActionServerElements();
		this.pRosActionClient = new RosActionClientElements();
		this.pRosParameter = new RosParameterElements();
		this.pEString = new EStringElements();
		this.pNS = new NSElements();
		this.pParameterValue = new ParameterValueElements();
		this.pParameterString = new ParameterStringElements();
		this.pParameterBase64 = new ParameterBase64Elements();
		this.pParameterInteger = new ParameterIntegerElements();
		this.pParameterDouble = new ParameterDoubleElements();
		this.pParameterBoolean = new ParameterBooleanElements();
		this.pParameterList = new ParameterListElements();
		this.pParameterArray = new ParameterArrayElements();
		this.pParameterStruct = new ParameterStructElements();
		this.pParameterStructMember = new ParameterStructMemberElements();
		this.tDIGIT = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "de.fraunhofer.ipa.componentInterface.ComponentInterface.DIGIT");
		this.tBINARY = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "de.fraunhofer.ipa.componentInterface.ComponentInterface.BINARY");
		this.tBOOLEAN = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "de.fraunhofer.ipa.componentInterface.ComponentInterface.BOOLEAN");
		this.tDOUBLE = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "de.fraunhofer.ipa.componentInterface.ComponentInterface.DOUBLE");
		this.tDECINT = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "de.fraunhofer.ipa.componentInterface.ComponentInterface.DECINT");
		this.tDAY = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "de.fraunhofer.ipa.componentInterface.ComponentInterface.DAY");
		this.tMONTH = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "de.fraunhofer.ipa.componentInterface.ComponentInterface.MONTH");
		this.tYEAR = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "de.fraunhofer.ipa.componentInterface.ComponentInterface.YEAR");
		this.tHOUR = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "de.fraunhofer.ipa.componentInterface.ComponentInterface.HOUR");
		this.tMIN_SEC = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "de.fraunhofer.ipa.componentInterface.ComponentInterface.MIN_SEC");
		this.tDATE_TIME = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "de.fraunhofer.ipa.componentInterface.ComponentInterface.DATE_TIME");
		this.pBase64Binary = new Base64BinaryElements();
		this.pBoolean0 = new Boolean0Elements();
		this.pDouble0 = new Double0Elements();
		this.pInteger0 = new Integer0Elements();
		this.pDateTime0 = new DateTime0Elements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("de.fraunhofer.ipa.componentInterface.ComponentInterface".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//ComponentInterface:
	//	'ComponentInterface'
	//	'{'
	//	'name' name=EString ('NameSpace' NameSpace=EString)? ('RosPublishers' '{' rospublisher+=RosPublisher (","
	//	rospublisher+=RosPublisher)* '}')? ('RosSubscribers' '{' rossubscriber+=RosSubscriber (","
	//	rossubscriber+=RosSubscriber)* '}')? ('RosSrvServers' '{' rosserviceserver+=RosServiceServer (","
	//	rosserviceserver+=RosServiceServer)* '}')? ('RosSrvClients' '{' rosserviceclient+=RosServiceClient (","
	//	rosserviceclient+=RosServiceClient)* '}')? ('RosActionServers' '{' rosactionserver+=RosActionServer (","
	//	rosactionserver+=RosActionServer)* '}')? ('RosActionClients' '{' rosactionclient+=RosActionClient (","
	//	rosactionclient+=RosActionClient)* '}')? ('RosParameters' '{' rosparameter+=RosParameter (","
	//	rosparameter+=RosParameter)* '}')?
	//	'}';
	public ComponentInterfaceElements getComponentInterfaceAccess() {
		return pComponentInterface;
	}
	
	public ParserRule getComponentInterfaceRule() {
		return getComponentInterfaceAccess().getRule();
	}
	
	//RosPublisher:
	//	{RosPublisher}
	//	'RosPublisher'
	//	name=EString?
	//	'{' ('ns' ns=EString)?
	//	'RefPublisher' publisher=[ros::Publisher|EString]
	//	'}';
	public RosPublisherElements getRosPublisherAccess() {
		return pRosPublisher;
	}
	
	public ParserRule getRosPublisherRule() {
		return getRosPublisherAccess().getRule();
	}
	
	//RosSubscriber:
	//	{RosSubscriber}
	//	'RosSubscriber'
	//	name=EString?
	//	'{' ('ns' ns=EString)?
	//	'RefSubscriber' subscriber=[ros::Subscriber|EString]
	//	'}';
	public RosSubscriberElements getRosSubscriberAccess() {
		return pRosSubscriber;
	}
	
	public ParserRule getRosSubscriberRule() {
		return getRosSubscriberAccess().getRule();
	}
	
	//RosServiceServer:
	//	{RosServiceServer}
	//	'RosServiceServer'
	//	name=EString?
	//	'{' ('ns' ns=EString)?
	//	'RefServer' srvserver=[ros::ServiceServer|EString]
	//	'}';
	public RosServiceServerElements getRosServiceServerAccess() {
		return pRosServiceServer;
	}
	
	public ParserRule getRosServiceServerRule() {
		return getRosServiceServerAccess().getRule();
	}
	
	//RosServiceClient:
	//	{RosServiceClient}
	//	'RosServiceClient'
	//	name=EString?
	//	'{' ('ns' ns=EString)?
	//	'RefClient' srvclient=[ros::ServiceClient|EString]
	//	'}';
	public RosServiceClientElements getRosServiceClientAccess() {
		return pRosServiceClient;
	}
	
	public ParserRule getRosServiceClientRule() {
		return getRosServiceClientAccess().getRule();
	}
	
	//RosActionServer:
	//	{RosActionServer}
	//	'RosActionServer'
	//	name=EString?
	//	'{' ('ns' ns=EString)?
	//	'RefServer' actserver=[ros::ActionServer|EString]
	//	'}';
	public RosActionServerElements getRosActionServerAccess() {
		return pRosActionServer;
	}
	
	public ParserRule getRosActionServerRule() {
		return getRosActionServerAccess().getRule();
	}
	
	//RosActionClient:
	//	{RosActionClient}
	//	'RosActionClient'
	//	name=EString?
	//	'{' ('ns' ns=EString)?
	//	'RefClient' actclient=[ros::ActionClient|EString]
	//	'}';
	public RosActionClientElements getRosActionClientAccess() {
		return pRosActionClient;
	}
	
	public ParserRule getRosActionClientRule() {
		return getRosActionClientAccess().getRule();
	}
	
	//RosParameter:
	//	{RosParameter}
	//	'RosParameter'
	//	name=EString?
	//	'{' ('ns' ns=EString)?
	//	'RefParameter' parameter=[ros::Parameter|EString] ('value' value=ParameterValue)?
	//	'}';
	public RosParameterElements getRosParameterAccess() {
		return pRosParameter;
	}
	
	public ParserRule getRosParameterRule() {
		return getRosParameterAccess().getRule();
	}
	
	//EString:
	//	STRING | ID;
	public EStringElements getEStringAccess() {
		return pEString;
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}
	
	//NS NS:
	//	'NS' /* TODO: implement this rule and an appropriate IValueConverter */;
	public NSElements getNSAccess() {
		return pNS;
	}
	
	public ParserRule getNSRule() {
		return getNSAccess().getRule();
	}
	
	//// PARAMETERS!!
	//ParameterValue ros::ParameterValue:
	//	ParameterDouble | ParameterBoolean | ParameterInteger | ParameterBase64 | ParameterList | ParameterStruct |
	//	ParameterString;
	public ParameterValueElements getParameterValueAccess() {
		return pParameterValue;
	}
	
	public ParserRule getParameterValueRule() {
		return getParameterValueAccess().getRule();
	}
	
	//ParameterString ros::ParameterString:
	//	value=EString;
	public ParameterStringElements getParameterStringAccess() {
		return pParameterString;
	}
	
	public ParserRule getParameterStringRule() {
		return getParameterStringAccess().getRule();
	}
	
	//ParameterBase64 ros::ParameterBase64:
	//	value=Base64Binary;
	public ParameterBase64Elements getParameterBase64Access() {
		return pParameterBase64;
	}
	
	public ParserRule getParameterBase64Rule() {
		return getParameterBase64Access().getRule();
	}
	
	//ParameterInteger ros::ParameterInteger:
	//	value=Integer0;
	public ParameterIntegerElements getParameterIntegerAccess() {
		return pParameterInteger;
	}
	
	public ParserRule getParameterIntegerRule() {
		return getParameterIntegerAccess().getRule();
	}
	
	//ParameterDouble ros::ParameterDouble:
	//	value=Double0;
	public ParameterDoubleElements getParameterDoubleAccess() {
		return pParameterDouble;
	}
	
	public ParserRule getParameterDoubleRule() {
		return getParameterDoubleAccess().getRule();
	}
	
	//ParameterBoolean ros::ParameterBoolean:
	//	value=boolean0;
	public ParameterBooleanElements getParameterBooleanAccess() {
		return pParameterBoolean;
	}
	
	public ParserRule getParameterBooleanRule() {
		return getParameterBooleanAccess().getRule();
	}
	
	//ParameterList ros::ParameterSequence:
	//	{ros::ParameterSequence}
	//	'{' value+=ParameterValue (',' value+=ParameterValue)* '}';
	public ParameterListElements getParameterListAccess() {
		return pParameterList;
	}
	
	public ParserRule getParameterListRule() {
		return getParameterListAccess().getRule();
	}
	
	//ParameterArray ros::ParameterSequence:
	//	{ros::ParameterSequence}
	//	'{' value+=ParameterValue (',' value+=ParameterValue)* '}';
	public ParameterArrayElements getParameterArrayAccess() {
		return pParameterArray;
	}
	
	public ParserRule getParameterArrayRule() {
		return getParameterArrayAccess().getRule();
	}
	
	//ParameterStruct ros::ParameterStruct:
	//	{ros::ParameterStruct} ('{' value+=ParameterStructMember ("," value+=ParameterStructMember)* '}')?;
	public ParameterStructElements getParameterStructAccess() {
		return pParameterStruct;
	}
	
	public ParserRule getParameterStructRule() {
		return getParameterStructAccess().getRule();
	}
	
	//ParameterStructMember ros::ParameterStructMember:
	//	name=EString
	//	'{'
	//	'value' value=ParameterValue
	//	'}';
	public ParameterStructMemberElements getParameterStructMemberAccess() {
		return pParameterStructMember;
	}
	
	public ParserRule getParameterStructMemberRule() {
		return getParameterStructMemberAccess().getRule();
	}
	
	//terminal fragment DIGIT:
	//	'0'..'9';
	public TerminalRule getDIGITRule() {
		return tDIGIT;
	}
	
	//terminal BINARY:
	//	('0b' | '0B') ('0' | '1')+;
	public TerminalRule getBINARYRule() {
		return tBINARY;
	}
	
	//terminal BOOLEAN:
	//	'true' | 'false';
	public TerminalRule getBOOLEANRule() {
		return tBOOLEAN;
	}
	
	//terminal DOUBLE returns ecore::EDouble:
	//	DECINT ('.' DIGIT* | ('.' DIGIT*)? ('E' | 'e') ('-' | '+')? DECINT);
	public TerminalRule getDOUBLERule() {
		return tDOUBLE;
	}
	
	//terminal DECINT:
	//	'0' | '1'..'9' DIGIT* | '-' '1'..'9' DIGIT*;
	public TerminalRule getDECINTRule() {
		return tDECINT;
	}
	
	//terminal DAY:
	//	'1'..'9' | '1'..'3' '0'..'9';
	public TerminalRule getDAYRule() {
		return tDAY;
	}
	
	//terminal MONTH:
	//	'1'..'9' | '1' '0'..'2';
	public TerminalRule getMONTHRule() {
		return tMONTH;
	}
	
	//terminal YEAR:
	//	'0'..'2' '0'..'9' '0'..'9' '0'..'9';
	public TerminalRule getYEARRule() {
		return tYEAR;
	}
	
	//terminal HOUR:
	//	'0'..'1' '0'..'9' | '2' '0'..'3';
	public TerminalRule getHOURRule() {
		return tHOUR;
	}
	
	//terminal MIN_SEC:
	//	'0'..'5' '0'..'9';
	public TerminalRule getMIN_SECRule() {
		return tMIN_SEC;
	}
	
	//terminal DATE_TIME:
	//	YEAR '-' MONTH '-' DAY 'T' HOUR ':' MIN_SEC ':' MIN_SEC;
	public TerminalRule getDATE_TIMERule() {
		return tDATE_TIME;
	}
	
	//Base64Binary type::Base64Binary:
	//	BINARY;
	public Base64BinaryElements getBase64BinaryAccess() {
		return pBase64Binary;
	}
	
	public ParserRule getBase64BinaryRule() {
		return getBase64BinaryAccess().getRule();
	}
	
	//boolean0 type::Boolean:
	//	BOOLEAN;
	public Boolean0Elements getBoolean0Access() {
		return pBoolean0;
	}
	
	public ParserRule getBoolean0Rule() {
		return getBoolean0Access().getRule();
	}
	
	//Double0 type::Double:
	//	DOUBLE;
	public Double0Elements getDouble0Access() {
		return pDouble0;
	}
	
	public ParserRule getDouble0Rule() {
		return getDouble0Access().getRule();
	}
	
	//Integer0 type::Int:
	//	DECINT;
	public Integer0Elements getInteger0Access() {
		return pInteger0;
	}
	
	public ParserRule getInteger0Rule() {
		return getInteger0Access().getRule();
	}
	
	//DateTime0 type::DateTime:
	//	DATE_TIME;
	public DateTime0Elements getDateTime0Access() {
		return pDateTime0;
	}
	
	public ParserRule getDateTime0Rule() {
		return getDateTime0Access().getRule();
	}
	
	//terminal ID:
	//	'^'? ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//	'"' ('\\' . | !('\\' | '"'))* '"' |
	//	"'" ('\\' . | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT:
	//	'/*'->'*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
