/**
 * generated by Xtext 2.12.0
 */
package de.fraunhofer.ipa.ros;

import de.fraunhofer.ipa.ros.AbstractRosRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class RosRuntimeModule extends AbstractRosRuntimeModule {
}
