/*
 * generated by Xtext 2.25.0
 */
package de.fraunhofer.ipa.ros2.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class Ros2UiModule extends AbstractRos2UiModule {

	public Ros2UiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
