/*
 * generated by Xtext 2.12.0
 */
package de.fraunhofer.ipa.ros.validation
import org.eclipse.xtext.validation.Check
import ros.Node
import ros.Artifact
import ros.Package
import ros.Publisher
import ros.Subscriber
import ros.ServiceServer
import ros.ServiceClient
import ros.ActionClient
import ros.ActionServer

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class RosValidator extends AbstractRosValidator {

  public static val INVALID_NAME = 'invalidName'
  
  /* CAPITAL LETTERS */
  @Check
  def void checkNameConventionsNode (Node node) {
  	for (char c : node.name.toCharArray){
  		if (Character.isUpperCase(c)){
  			warning("The name of a node should follow the ROS naming conventions: Capital letters are not recommended", null, INVALID_NAME);
  		}
  	}}
  @Check
  def void checkNameConventionsArtifact (Artifact artifact) {
  	for (char c : artifact.name.toCharArray){
  		if (Character.isUpperCase(c)){
  			warning("The name of a artifact should follow the ROS naming conventions: Capital letters are not recommended", null, INVALID_NAME);
  		}
  	}}
  @Check
  def void checkNameConventionsPackage (Package rospackage) {
	for (char c : rospackage.name.toCharArray){
		if (Character.isUpperCase(c)){
			error("The name of a package has to follow the ROS naming conventions: Capital letters are not allowed", null, INVALID_NAME);
		}
 	}
  }
  
  /* Customize Syntax Error Messages */
  
   public static val INVALID_SPEC = 'invalidSpecRef'
   public static String SpecWarning = "## Quick Fixes available ##-
    - Add the dependency to the specifications project
    - Generate the .ros model for the specifications
      ->https://github.com/ipa320/ros-model/blob/master/docu/NewCommunicationObjects.md"
  
  /* For Topics */
  @Check
  def void CheckMsgsRefPublisher(Publisher pub){
  	if(pub.message.eContainer === null){
  		warning( SpecWarning, null, INVALID_SPEC)
  	}
  }
  
  @Check
  def void CheckMsgsRefSubscriber(Subscriber sub){
  	if(sub.message.eContainer === null){
  		warning( SpecWarning, null, INVALID_SPEC)
  	}
  }
  
  /* For Actions */
  @Check
  def void CheckMsgsRefActionClient(ActionClient act){
  	if(act.action.eContainer === null){
  		warning( SpecWarning, null, INVALID_SPEC)
  	}
  }
  
   @Check
  def void CheckMsgsRefActionServer(ActionServer act){
  	if(act.action.eContainer === null){
  		warning( SpecWarning, null, INVALID_SPEC)
  	}
  }
  
  /* For Services */
  @Check
  def void CheckMsgsRefServiceServer (ServiceServer ser){
  	if(ser.service.eContainer === null){
  		warning( SpecWarning, null, INVALID_SPEC)
  	}
  }
  
  @Check
  def void CheckMsgsRefServiceClient (ServiceClient ser){
  	if(ser.service.eContainer === null){
  		warning( SpecWarning, null, INVALID_SPEC)
  	}
  }
 
   //The RULE_ID impose the rest of the ROS naming convention rules : bin/de/fraunhofer/ipa/ros/parser/antlr/internal/InternalRos.g
  // allow the use only of the symbol: "_"
  // allow the use of numbers
  
 }


