/*
 * generated by Xtext 2.30.0
 */
package de.fraunhofer.ipa.ros1.scoping;

import de.fraunhofer.ipa.ros.scoping.RosScopeProvider;

public abstract class AbstractRos1ScopeProvider extends RosScopeProvider {
}
