/*
 * generated by Xtext 2.12.0
 */
package de.fraunhofer.ipa.ide


/**
 * Use this class to register ide components.
 */
class ComponentInterfaceIdeModule extends AbstractComponentInterfaceIdeModule {
}
