name: RosTooling CI

on: [push,pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: RosTooling
    - name: Install jdk 19
      run: sudo apt install -y openjdk-19-jre
    - name: Install maven
      run: sudo apt install -y maven
    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '19'
    - name: Debug
      run: |
        uname -a
        mvn --version
        java --version
    - name: Build and test with Maven
      run: |
        pushd RosTooling
        mvn clean verify -f plugins/de.fraunhofer.ipa.ros.parent/pom.xml
