name: ros-model CI

on: [push,pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install java environmetn
      run: sudo apt-get install -y openjdk-19-jre

    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: ros-model
    - name: Build and test with Maven
      run: |
        pushd ros-model
        mvn clean verify -f plugins/de.fraunhofer.ipa.ros.parent/pom.xml
